AddonId: Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e
Packages:
  - Version: 2.13
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-08-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.08.07_57c08120/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_13.pext
    Changelog:
    - 'Extension rewritten as a plugin and renamed extension to "Purchase Date Importer"'
    - 'Added window that contains actions to import or export licenses'
  - Version: 2.14
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-08-10
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.08.10_7d122a68/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_14.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.15
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-08-21
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.08.21_54d33423/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_15.pext
    Changelog:
    - 'Improved stability of internet downloads'
  - Version: 2.16
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-08-31
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.08.31_1935a6a1/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_16.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.17
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-01-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.01.07_6064640d/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_17.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.18
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-02-06
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.02.06_002184fc/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_18.pext
    Changelog:
    - 'Added additional logging'
  - Version: 2.19
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-02-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.02.15_7796d0ce/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_19.pext
    Changelog:
    - 'Updated links'
  - Version: 2.20
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-03-02
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.03.02_2c8b4ab9/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_20.pext
    Changelog:
    - 'Fix crash when importing EA license data'
  - Version: 2.21
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-07-19
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.07.19_7051579c/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_21.pext
    Changelog:
    - 'Fix failing to obtain Epic library licenses'
  - Version: 2.22
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-08-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.08.18_ceff63a9/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_22.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.23
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-11-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.11.11_3bf6575c/Date_Importer_d0e7fb90-e74e-4955-b7bc-43a13339637e_2_23.pext
    Changelog:
    - 'Improved: Processing of internet requests'