AddonId: Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_2.pext
    Changelog:
    - Updated localizations
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_3.pext
    Changelog:
    - Updated localizations
    - Fix localization file not loading due to duplicate localization key
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-22
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta4/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_4.pext
    Changelog:
    - Rewritten as plugin extension. Work in progress and certain previous available features missing.
    - Added control to display steam reviews in compatible themes
  - Version: 2.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-22
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta4/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_5.pext
    Changelog:
    - Updated extension icon
  - Version: 2.6
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_6.pext
    Changelog:
    - Updated localizations
    - Update to PlayniteSDK.6.0.0
    - Show total play time in reviews
    - Option to show reviews helpfulness
    - Fix not correctly showing results dialogue when updating reviews
    - Fix showing forever playtime instead of playtime at review
    - Fix small unresponsiveness when switching games
    - Fix displaying incorrect number of hours when time exceeds 24 hours
  - Version: 2.7
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_7.pext
    Changelog:
    - Updated localizations
  - Version: 2.8
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_8.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.1.0
  - Version: 2.9
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_9.pext
    Changelog:
    - Updated localizations
  - Version: 2.10
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_10.pext
    Changelog:
    - Updated localizations
  - Version: 2.11
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-01
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_11.pext
    Changelog:
    - Updated localizations
  - Version: 2.12
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-21
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_12.pext
    Changelog:
    - Updated localizations
    - Fix some display data not properly updating on changes
  - Version: 2.13
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-11-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_13.pext
    Changelog:
    - Optimize extension controls processing by stopping execution if control is not in current active view in Playnite
  - Version: 2.14
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_14.pext
    Changelog:
    - Reworked renderer for reviews viewer control to improve formatting and make links clickable
  - Version: 2.15
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_15.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.2.2
  - Version: 2.16
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_16.pext
    Changelog:
    - Updated localizations
  - Version: 2.17
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_17.pext
    Changelog:
    - Updated localizations
  - Version: 2.18
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-08
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_18.pext
    Changelog:
    - Updated localizations
  - Version: 2.19
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_19.pext
    Changelog:
    - Improved extension codebase structure
    - Misc improvements
  - Version: 2.20
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_20.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.21
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.20_b118c6cd/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_21.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.22
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-23
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.23_32f4ed05/Review_Viewer_ca24e37a-76d9-49bf-89ab-d3cba4a54bd1_2_22.pext
    Changelog:
    - 'Updated localizations'
    - 'Fix crash when downloaded Steam review data was not succesful'
    - 'Added option to display review date (Enabled by default)'