AddonId: CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_0.pext
    Changelog:
    - Updated localizations
  - Version: 1.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_1.pext
    Changelog:
    - Updated localizations
    - Added option to enable or disable importing of basic features
    - Added option to enable or disable importing of detailed features
    - Added options to enable or disable importing of specific detailed features
    - Added option to import Co-Optimus link during importing
    - Fixes and improvements to game matching with database
    - Updated database
  - Version: 1.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_2.pext
    Changelog:
    - Updated localizations
  - Version: 1.3
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-03
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_3.pext
    Changelog:
    - Updated localizations
    - 'Improve game matching when name uses "&" character'
    - 'Added search function to manually select database entry'
  - Version: 1.4
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_4.pext
    Changelog:
    - Updated localizations
  - Version: 1.5
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_5.pext
    Changelog:
    - Improved extension codebase structure
    - Misc improvements
  - Version: 1.6
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_6.pext
    Changelog:
    - 'Update Co-Optimus database used by the extension'
  - Version: 1.7
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_7.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.8
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.25_5ef4228b/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_8.pext
    Changelog:
    - 'Update Co-Optimus database used by the extension'
  - Version: 1.9
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.25_aae44e45/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_9.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.10
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.30_901ef791/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_10.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.11
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-02
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.02_01d659e6/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_11.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.12
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.15_9bdaf3ae/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_12.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.13
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-06-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.06.11_f6b6813d/CooperativeModesImporter_9767ac15-6e26-4e4c-9d69-f6838625dde3_1_13.pext
    Changelog:
    - 'Performance improvements to games processing'
    - 'Update Co-Optimus database used by the extension'