AddonId: NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-09
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_0.pext
    Changelog:
    - Initial release
  - Version: 1.1
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-21
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_1.pext
    Changelog:
    - Updated localizations
  - Version: 1.2
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-11-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_2.pext
    Changelog:
    - Optimize extension controls processing by stopping execution if control is not in current active view in Playnite
    - Added icon
  - Version: 1.3
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_3.-.copia.pext
    Changelog:
    - Reworked renderer for news control text to improve formatting, display images and make links clickable
  - Version: 1.4
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_4.pext
    Changelog:
    - Updated localizations
    - Added option to show Steam news for games not from Steam
  - Version: 1.5
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_5.pext
    Changelog:
    - Updated localizations
  - Version: 1.6
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_6.pext
    Changelog:
    - Updated localizations
  - Version: 1.7
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_7.pext
    Changelog:
    - Updated localizations
  - Version: 1.8
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_8.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.2.2
  - Version: 1.9
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_9.pext
    Changelog:
    - Updated localizations
  - Version: 1.10
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_10.pext
    Changelog:
    - Updated localizations
  - Version: 1.11
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_11.pext
    Changelog:
    - Improved extension codebase structure
    - Misc improvements
  - Version: 1.12
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_12.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.13
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.25_aae44e45/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_13.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.14
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.30_901ef791/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_14.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.15
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-02
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.02_01d659e6/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_15.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.16
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.15_9bdaf3ae/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_16.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.17
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-06-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.06.18_251f0687/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_17.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.18
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-07-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.07.28_1dac80c6/NewsViewer_15e03ffe-90f6-4e8e-bd4d-94514777481d_1_18.pext
    Changelog:
    - 'News will be scrolled to the top when it changes'