AddonId: SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-10
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748_1_0.pext
    Changelog:
    - Initial release
  - Version: 1.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-10
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748_1_1.pext
    Changelog:
    - Updated localizations
    - Added option to not start services if game is detected as using EasyAntiCheat
    - Added button to profiles editor to delete the selected profile
  - Version: 1.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748_1_2.pext
    Changelog:
    - Updated localizations
  - Version: 1.3
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748_1_3.pext
    Changelog:
    - Updated localizations
    - Clicking an error notification will open the Wiki help article
    - Improved detection of missing Special K files
  - Version: 1.4
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748_1_4.pext
    Changelog:
    - Improved extension codebase structure
    - Misc improvements
  - Version: 1.5
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748_1_5.pext
    Changelog:
    - 'Fix Special K Editor not opening if an ini has duplicate keys'
    - 'Fix using checkbox to switch fuzzy search not refreshing the results'
    - 'Lower fuzzy search threshold in Profiles Editor'
  - Version: 1.6
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748_1_6.pext
    Changelog:
    - 'Fix Special K Profiles Editor not opening if an ini has duplicate sections'
  - Version: 1.7
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748_1_7.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.8
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.25_aae44e45/SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748_1_8.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.9
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.30_901ef791/SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748_1_9.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.10
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-02
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.02_01d659e6/SpecialKHelper_71349310-9ed8-4bf5-8bf2-e92cdb222748_1_10.pext
    Changelog:
    - 'Updated localizations'