AddonId: NVIDIA_GeForce_Now_Enabler
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/NVIDIA_GeForce_Now_Enabler_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/NVIDIA_GeForce_Now_Enabler_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/NVIDIA_GeForce_Now_Enabler_2_2.pext
    Changelog:
    - Updated localizations
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/NVIDIA_GeForce_Now_Enabler_2_3.pext
    Changelog:
    - Updated localizations
    - Update to PlayniteSDK.6.0.0
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/NVIDIA_GeForce_Now_Enabler_2_4.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.1.0
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/NVIDIA_GeForce_Now_Enabler_2_5.pext
    Changelog:
    - Updated localizations
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/NVIDIA_GeForce_Now_Enabler_2_6.pext
    Changelog:
    - Updated localizations
    - Play Actions are no longer added to games
    - Play Actions are automatically made available for compatible games upon launch
  - Version: 2.7
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-31
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/NVIDIA_GeForce_Now_Enabler_2_7.pext
    Changelog:
    - Minor internal improvements
  - Version: 2.8
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-01
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/NVIDIA_GeForce_Now_Enabler_2_8.pext
    Changelog:
    - Updated localizations
  - Version: 2.9
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/NVIDIA_GeForce_Now_Enabler_2_9.pext
    Changelog:
    - Updated localizations
  - Version: 2.10
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-21
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/NVIDIA_GeForce_Now_Enabler_2_10.pext
    Changelog:
    - Updated localizations
    - Improve game matching of certain games with database
    - Always mark games as installed when option to show Play Actions is enabled
  - Version: 2.11
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-23
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/NVIDIA_GeForce_Now_Enabler_2_11.pext
    Changelog:
    - Updated localizations
  - Version: 2.12
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/NVIDIA_GeForce_Now_Enabler_2_12.pext
    Changelog:
    - Updated localizations
  - Version: 2.13
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/NVIDIA_GeForce_Now_Enabler_2_13.pext
    Changelog:
    - Updated localizations
    - Show notification when games are marked as installed or uninstalled and a dialog is not shown
    - Fix some Origin games not being matched with GeForce NOW database
  - Version: 2.14
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/NVIDIA_GeForce_Now_Enabler_2_14.pext
    Changelog:
    - Updated localizations
  - Version: 2.15
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-22
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/NVIDIA_GeForce_Now_Enabler_2_15.pext
    Changelog:
    - Updated localizations
  - Version: 2.16
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/NVIDIA_GeForce_Now_Enabler_2_16.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.2.2
  - Version: 2.17
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/NVIDIA_GeForce_Now_Enabler_2_17.pext
    Changelog:
    - Updated localizations
  - Version: 2.18
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/NVIDIA_GeForce_Now_Enabler_2_18.pext
    Changelog:
    - Updated localizations
  - Version: 2.19
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/NVIDIA_GeForce_Now_Enabler_2_19.pext
    Changelog:
    - Updated localizations
  - Version: 2.20
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/NVIDIA_GeForce_Now_Enabler_2_20.pext
    Changelog:
    - Improved extension codebase structure
    - Misc improvements
  - Version: 2.21
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/NVIDIA_GeForce_Now_Enabler_2_21.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.22
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.25_aae44e45/NVIDIA_GeForce_Now_Enabler_2_22.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.23
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.30_901ef791/NVIDIA_GeForce_Now_Enabler_2_23.pext
    Changelog:
    - 'Fix entry detection failing after latest changes in GeForce NOW database'
  - Version: 2.24
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.30_a5bb55cf/NVIDIA_GeForce_Now_Enabler_2_24.pext
    Changelog:
    - 'Fix not correctly detecting GeForce NOW executable on game launch'
  - Version: 2.25
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-02
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.02_01d659e6/NVIDIA_GeForce_Now_Enabler_2_25.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.26
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-02
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.02_ddc118cd/NVIDIA_GeForce_Now_Enabler_2_26.pext
    Changelog:
    - 'Rework how plugin obtains GeForce Now database data'
    - 'General improvements for detection of supported games'
  - Version: 2.27
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-03
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.03_3ad2d023/NVIDIA_GeForce_Now_Enabler_2_27.pext
    Changelog:
    - 'Added option to indicate if GeForce Now Play Action should be shown for games that are already installed by their libraries'
    - 'Added main menu item to open a window with a database browser to view games available on the GeForce NOW service. Game names can be copied from right click context menu.'
  - Version: 2.28
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.07_98fa5f6c/NVIDIA_GeForce_Now_Enabler_2_28.pext
    Changelog:
    - 'Updated localizations'