AddonId: Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_1.pext
    Changelog:
      - Updated localizations
      - Fix SteamGridDB logo download function missing
      - Add function to remove unused data
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_2.pext
    Changelog:
    - Updated localizations
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_3.pext
    Changelog:
    - Updated localizations
    - Fix error when trying to display a specific dialog
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-31
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_5.pext
    Changelog:
    - Removed deprecated functions and most functions related to logos functionality
    - 'Note: Functionality of removed functions have been reimplemented in the "Extra Metadata Loader" extension'
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-01
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_6.pext
    Changelog:
    - Updated localizations
    - Reorganized menu items
    - Removed some deprecated functionality
    - 'Note: Functionality of removed functions have been reimplemented in the "Extra Metadata Loader" extension that needs to be installed separately'
  - Version: 2.7
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-04
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_7.pext
    Changelog:
    - 'Renamed extension to "Extra Metadata Fullscreen Mode Helper"'
    - Removed all functionality related to logos download
    - 'Note: Functionality of removed functions have been reimplemented and improved in the "Extra Metadata Loader" extension that needs to be installed separately'
  - Version: 2.8
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-09
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_8.pext
    Changelog:
    - Updated localizations
  - Version: 2.9
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_9.pext
    Changelog:
    - Updated localizations
  - Version: 2.10
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_10.pext
    Changelog:
    - Updated localizations
  - Version: 2.11
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_11.pext
    Changelog:
    - Updated localizations
  - Version: 2.12
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-11-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.11.14_873c946b/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_12.pext
    Changelog:
    - 'Fix extension corrupting theme if Windows user contains certain characters'
  - Version: 2.13
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-08-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.08.18_ceff63a9/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_13.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.14
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-09-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.09.27_1fcfc18d/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_14.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 2.15
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-11-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.11.28_0f949552/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_15.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 2.16
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2024-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.03.17_527a9df9/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_16.pext
    Changelog:
    - 'Changed: Updated localizations'
  - Version: 2.17
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2024-05-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2024.05.12_b43337e1/Extra_Metadata_tools_2e0349ed-6da2-4095-9457-4c9fb544551e_2_17.pext
    Changelog:
    - 'Changed: Updated localizations'