AddonId: ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_0.pext
    Changelog:
    - Initial release
  - Version: 1.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_1.pext
    Changelog:
    - Updated localizations
    - Fix videos starting playing at second 1 when repeating
  - Version: 1.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_2.pext
    Changelog:
    - Fix icons in buttons of video player not showing if font is not installed
  - Version: 1.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_3.pext
    Changelog:
    - Add NewContextVideoAvailable and IsPlaying settings path available for theme developers
    - Fix source switch button changes not applying when selecting a new game
  - Version: 1.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_4.pext
    Changelog:
    - Updated localizations
  - Version: 1.5
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-22
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta4/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_5.pext
    Changelog:
    - Updated localizations
  - Version: 1.6
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-22
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta4/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_6.pext
    Changelog:
    - Updated localizations
  - Version: 1.7
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_7.pext
    Changelog:
    - Updated localizations
    - Update to PlayniteSDK.6.0.0
    - Option to stream trailer videos from Steam on demand
    - Split logo and video settings in tabs
    - Options to enable or disable logo effect and configure its depth, direction, blur radius and opacity
    - Fix small unresponsiveness when loading logos
  - Version: 1.8
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-01
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_8.pext
    Changelog:
    - Fix playback bar and slider progress being misaligned
  - Version: 1.9
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_9.pext
    Changelog:
    - Updated localizations
    - Changed color of logo shadow effect
  - Version: 1.10
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_10.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.1.0
  - Version: 1.11
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_11.pext
    Changelog:
    - Updated localizations
  - Version: 1.12
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_12.pext
    Changelog:
    - Updated localizations
  - Version: 1.13
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-31
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_13.pext
    Changelog:
    - Updated localizations
    - Added functionality to download logos from Steam
    - Added functionality to download logos from SteamGridDB
    - Added optional functionality to automatically download logos for newly added games on library update
    - Added functionality to remove Extra Metadata data when a game is removed from Playnite database
  - Version: 1.14
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-31
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_14.pext
    Changelog:
    - Updated localizations
    - Fix steam searches not working due to using different dependency version than Playnite
    - Notify is SteamGridDB API Key has not been configured during logos download
  - Version: 1.15
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-31
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_15.pext
    Changelog:
    - Fix steam manual search not initially using the game name
  - Version: 1.16
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-01
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_16.pext
    Changelog:
    - Updated localizations
    - Remove Extra Metadata directory of Sources and Platforms when they are removed from Playnite
    - Reorganized menu items
    - Added options to automatically trim and resize down logos after downloading
    - Add options to update tags that indicate if a game Extra Metadata asset is missing on library update
  - Version: 1.17
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-04
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_17.pext
    Changelog:
    - Updated localizations
    - Added menu items with functionality to download videos and micro videos from Steam
    - Added setting to configure if videos from Steam should be downloaded in High Definition quality
    - Added option to download Steam videos for newly added games on library update
    - Optimize media downloads from Steam by not executing them for games that are not from Steam or PC games
    - Added menu item with functionality to generate micro videos from download game videos
    - Added menu items to delete downloaded videos and micro videos
    - Added menu item to search and download videos from YouTube using yt-dlp
    - 'Added option to configure path to "cookies.txt" file for yt-dlp to allow downloading age restricted videos'
    - Added button in settings to login to youtube to allow viewing age restricted videos in the full version of the site when using the YouTube search window
    - Added menu item to search and download logos from Google
    - General fixes and improvements
  - Version: 1.18
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_18.pext
    Changelog:
    - Updated localizations
    - Fix using incorrect name of yt-dlp in texts and dialogs
    - "Automatically redirect to full YouTube site version for videos that can't be viewed in the embedded player"
    - Added option to configure if only Steam and PC games should be processed when obtaining metadata from Steam
    - Improved automatic game matching when searching for logos from SteamGridDB
    - Make certain processes cancelable in progress dialog
  - Version: 1.19
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_19.pext
    Changelog:
    - Fix detection of micro videos when adding tags not working correctly
  - Version: 1.20
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_20.pext
    Changelog:
    - Updated localizations
  - Version: 1.21
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-21
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_21.pext
    Changelog:
    - Updated localizations
    - Add menu item to set logo from selected file
    - Show game name in caption of logo download windows
  - Version: 1.22
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-23
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_22.pext
    Changelog:
    - Updated localizations
    - Fix setting logo from file not working if processing of logos is disabled
  - Version: 1.23
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-11-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_23.pext
    Changelog:
    - Optimize extension controls processing by stopping execution if control is not in current active view in Playnite
  - Version: 1.24
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-11-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_24.pext
    Changelog:
    - Updated localizations
    - Video in player now gets automatically refreshed after using a function in the extension related to videos
    - Videos no longer stop playing when Playnite is not the top window
    - Videos now get paused when a game is starting
  - Version: 1.25
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-11-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_25.pext
    Changelog:
    - "Fix to prevent video from playing if theme doesn't initally show the video player when autoplay has been enabled in settings"
  - Version: 1.26
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_26.pext
    Changelog:
    - Updated localizations
    - Added optional function to add menu items toview the review, gameplay video or open a search from YouTube of the selected game
    - Added option to configure if the video image should be displayed when the video is paused
    - Added option and functionality for custom themes to implement an alternative video player in views (Can be used to provide different locations for the video player in the same theme)
  - Version: 1.27
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_27.pext
    Changelog:
    - Updated localizations
  - Version: 1.28
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-09
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_28.pext
    Changelog:
    - Updated localizations
    - Added options to configure if logos marked as humor or nsfw should be included in searches
  - Version: 1.29
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_29.pext
    Changelog:
    - Updated localizations
  - Version: 1.30
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/ExtraMetadataLoader_705fdbca-e1fc-4004-b839-1d040b8b4429_1_30.pext
    Changelog:
    - Updated localizations
    - "Don't show Pause/Play video buttons when they are not not useable"