AddonId: PlayState
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/PlayState_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/PlayState_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/PlayState_2_2.pext
    Changelog:
    - Updated localizations
  - Version: 2.3
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/PlayState_2_3.pext
    Changelog:
    - Updated localizations
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/PlayState_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/PlayState_2_5.pext
    Changelog:
    - Updated localizations
    - Removed AutoHotkey dependency
    - Suspend/Resume hotkey is configurable in settings
    - 'Game skip feature changed to "[PlayState] Blacklist"'
    - General fixes and improvements as part of the extension rewrite
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/PlayState_2_6.pext
    Changelog:
    - Updated localizations
    - "Add note in settings that indicates that used hotkey can't be used in other applications"
    - Changed default hotkey combination to Shift+Alt+A
  - Version: 2.7
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-01
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/PlayState_2_7.pext
    Changelog:
    - Updated localizations
  - Version: 2.8
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/PlayState_2_8.pext
    Changelog:
    - Updated localizations
    - Added optional functionality to substract suspended time from game playtime after it is stopped
    - Added optional functionality to only suspend playtime count when suspending the game. Game processes are not suspended with this suspension mode.
    - 'Added optional functionality to force the suspend only playtime and not game processes for games that have a feature named "[PlayState] Suspend Playtime only"'
    - Changed descriptions in suspend dialogs to reflect if game processes or only playtime count was suspended
  - Version: 2.9
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/PlayState_2_9.pext
    Changelog:
    - Updated localizations
    - Fix being able to save invalid hotkeys without modifiers in settings
    - Add menu items to configure or remove configuration to force playtime suspend only of selected games
  - Version: 2.10
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-09
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/PlayState_2_10.pext
    Changelog:
    - Updated localizations
  - Version: 2.11
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/PlayState_2_11.pext
    Changelog:
    - Updated localizations
  - Version: 2.12
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/PlayState_2_12.pext
    Changelog:
    - Fixed extension causing Playnite windows to not be centered when created when Playnite is not the foreground window
  - Version: 2.13
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/PlayState_2_13.pext
    Changelog:
    - Updated localizations
  - Version: 2.14
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-09
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/PlayState_2_14.pext
    Changelog:
    - Updated localizations
    - Improved support for Custom emulator profiles. Emulators using Builtin profiles are not supported.
    - Extension will now resume game if it is suspended and another game is started
  - Version: 2.15
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/PlayState_2_15.pext
    Changelog:
    - Updated localizations
    - Fix extension not working with games not launched as emulated games
  - Version: 2.16
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/PlayState_2_16.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.2.2
    - Improvements during new Playtime calculation after game is closed
  - Version: 2.17
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/PlayState_2_17.pext
    Changelog:
    - Updated localizations
  - Version: 2.18
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/PlayState_2_18.pext
    Changelog:
    - Updated localizations
  - Version: 2.19
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-08
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/PlayState_2_19.pext
    Changelog:
    - "Added temporary workaround for sharing paused time with GameActivity extension (By BanCrash)"
  - Version: 2.20
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/PlayState_2_20.pext
    Changelog:
    - Updated localizations
    - 'Added option to display notifications as native Windows notifications. Enabled by default and only compatible with Windows10+. For full compatibility with games, it is required to configure Windows Focus Assist (By BanCrash)'
    - 'Added option to show total game playtime and session playtime in notifications. Enabled by default (By BanCrash)'
  - Version: 2.21
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/PlayState_2_21.pext
    Changelog:
    - Updated localizations
  - Version: 2.22
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/PlayState_2_22.pext
    Changelog:
    - Improved extension codebase structure
    - Misc improvements
  - Version: 2.23
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/PlayState_2_23.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.24
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.20_b118c6cd/PlayState_2_24.pext
    Changelog:
    - 'Fixed detection of processes to suspend for game Lost Ark'
  - Version: 2.25
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-23
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.23_32f4ed05/PlayState_2_25.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.26
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.25_aae44e45/PlayState_2_26.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.27
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-02
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.02_01d659e6/PlayState_2_27.pext
    Changelog:
    - 'Updated localizations'
    - 'Added support to add override feature to force to suspend game processes (By Bancrash)'
    - 'Added PlayState manager. Can be opened from sidebar'
    - 'Support to detect multiple game processes at the same time during game start'
    - 'Misc fixes and improvements'
  - Version: 2.28
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-02
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.02_ddc118cd/PlayState_2_28.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.29
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-03
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.03_3ad2d023/PlayState_2_29.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.30
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.15_9bdaf3ae/PlayState_2_30.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.31
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.18_1bfa38a6/PlayState_2_31.pext
    Changelog:
    - 'Fix extension no longetr working for Xbox Library games not installed in the main drive'
    - 'Fix error after suspending game when using toast notifications if game does not have a background image'
  - Version: 2.32
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-23
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.23_3f5693d2/PlayState_2_32.pext
    Changelog:
    - 'Updated localizations'
    - 'Previous game will be resumed if another game is launched and Playnite is running in Fullscreen Mode'
    - 'Show game icon in PlayState Manager grid'
    - 'Added column to PlayState Manager grid with buttons to suspend, resume and set a game as active'
    - 'Show cover image of active game in PlayState Manager'
  - Version: 2.33
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.25_222dfdd3/PlayState_2_33.pext
    Changelog:
    - 'Updated localizations'
    - 'Added PlayState Manager view for StartPage extension view'