AddonId: ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.3.0
    ReleaseDate: 2022-07-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.08.21_54d33423/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_0.pext
    Changelog:
    - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-10-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.10.20_fc05e8cf/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_1.pext
    Changelog:
    - 'Added support custom themes to define additional changes to be done when converting layout to Grid View'
    - 'Updated localizations'
  - Version: 1.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-01-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.01.07_6064640d/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_2.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.3
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-02-06
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.02.06_002184fc/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_3.pext
    Changelog:
    - 'Added additional logging'
  - Version: 1.4
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-02-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.02.15_7796d0ce/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_4.pext
    Changelog:
    - 'Updated links'
  - Version: 1.5
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-04-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.04.11_03a5475a/ThemesDetailsViewToGridViewConverter_ef8a7226-eedc-478d-a506-92ee6c088aa3_1_5.pext
    Changelog:
    - 'Updated localizations'