AddonId: Log_Open_a755c30f-580a-491e-9584-6c5314f6e254
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Log_Open_a755c30f-580a-491e-9584-6c5314f6e254_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/Log_Open_a755c30f-580a-491e-9584-6c5314f6e254_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Log_Open_a755c30f-580a-491e-9584-6c5314f6e254_2_2.pext
    Changelog:
    - Updated localizations
    - Fix extension icon not showing
  - Version: 2.3
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Log_Open_a755c30f-580a-491e-9584-6c5314f6e254_2_3.pext
    Changelog:
    - Updated localizations
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Log_Open_a755c30f-580a-491e-9584-6c5314f6e254_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/Log_Open_a755c30f-580a-491e-9584-6c5314f6e254_2_5.pext
    Changelog:
    - Updated localizations
  - Version: 2.6
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Log_Open_a755c30f-580a-491e-9584-6c5314f6e254_2_6.pext
    Changelog:
    - Updated localizations
  - Version: 2.7
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/Log_Open_a755c30f-580a-491e-9584-6c5314f6e254_2_7.pext
    Changelog:
    - Updated localizations