AddonId: GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_1.pext
    Changelog:
      - Updated localizations
      - Fix overview showing when no game is selected
      - Fix using an incorrect localization string during certain dialogs
      - Fix requesting the same catalog data twice
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_2.pext
    Changelog:
    - Updated localizations
    - Update to PlayniteSDK.6.0.0
  - Version: 2.3
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_3.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.1.0
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-09
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_5.pext
    Changelog:
    - Updated localizations
  - Version: 2.6
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_6.pext
    Changelog:
    - Updated localizations
    - Added button in catalog window to open game in Xbox app
  - Version: 2.7
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_7.pext
    Changelog:
    - Updated localizations
  - Version: 2.8
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_8.pext
    Changelog:
    - Updated localizations
  - Version: 2.9
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_9.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.2.2
  - Version: 2.10
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_10.pext
    Changelog:
    - Updated localizations
  - Version: 2.11
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_11.pext
    Changelog:
    - Updated localizations
  - Version: 2.12
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_12.pext
    Changelog:
    - Improved extension codebase structure
    - Misc improvements
    - Import default configured Completion Status for added games
  - Version: 2.13
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_13.pext
    Changelog:
    - 'Fix some games being added with an incorrect ReleaseDate to the Playnite library'
  - Version: 2.14
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_14.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.15
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-23
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.23_32f4ed05/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_15.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.16
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.25_aae44e45/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_16.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.17
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-03
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.03_3ad2d023/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_17.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.18
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-06-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.06.11_f6b6813d/GamePassCatalogBrowser_50c85177-570f-4494-be16-99d6aa5b8a93_2_18.pext
    Changelog:
    - 'Updated localizations'
    - 'Performance improvements to games processing'