AddonId: ExtraMetadataToolsVideo_008a6f60-9b4e-42b7-a799-18e66a6a7bd6
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/ExtraMetadataToolsVideo_008a6f60-9b4e-42b7-a799-18e66a6a7bd6_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/ExtraMetadataToolsVideo_008a6f60-9b4e-42b7-a799-18e66a6a7bd6_2_1.pext
    Changelog:
      - Updated localizations
      - Fix youtube video downloads failing if user paths contained spaces
      - Add channel name to Youtube search
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-22
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta4/ExtraMetadataToolsVideo_008a6f60-9b4e-42b7-a799-18e66a6a7bd6_2_2.pext
    Changelog:
    - Updated localizations
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/ExtraMetadataToolsVideo_008a6f60-9b4e-42b7-a799-18e66a6a7bd6_2_3.pext
    Changelog:
    - Updated localizations
    - Improved error handling for invalid videos
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/ExtraMetadataToolsVideo_008a6f60-9b4e-42b7-a799-18e66a6a7bd6_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/ExtraMetadataToolsVideo_008a6f60-9b4e-42b7-a799-18e66a6a7bd6_2_5.pext
    Changelog:
    - Updated localizations
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-01
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/ExtraMetadataToolsVideo_008a6f60-9b4e-42b7-a799-18e66a6a7bd6_2_6.pext
    Changelog:
    - Updated localizations
    - Reorganized menu items
    - Removed some deprecated functionality
    - 'Note: Functionality of removed functions have been reimplemented in the "Extra Metadata Loader" extension that needs to be installed separately'
  - Version: 2.7
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-04
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/ExtraMetadataToolsVideo_008a6f60-9b4e-42b7-a799-18e66a6a7bd6_2_7.pext
    Changelog:
    - Removed all functionality in the extension
    - 'Note: Functionality of removed functions have been reimplemented and improved in the "Extra Metadata Loader" extension that needs to be installed separately. This extension must be uninstalled as it does not provide any functionality anymore.'