AddonId: SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.3.0
    ReleaseDate: 2022-07-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.08.21_54d33423/SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac_1_0.pext
    Changelog:
    - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-01-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.01.07_6064640d/SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac_1_1.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.2
    RequiredApiVersion: 6.4.0
    ReleaseDate: 2023-02-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.02.15_7796d0ce/SteamSearch_78c7912a-32bb-4a42-8485-d348d10023ac_1_2.pext
    Changelog:
    - 'Updated links'