AddonId: Search_Collection
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Search_Collection_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/Search_Collection_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/Search_Collection_2_2.pext
    Changelog:
    - Updated localizations
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Search_Collection_2_3.pext
    Changelog:
    - Updated localizations
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Search_Collection_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Search_Collection_2_5.pext
    Changelog:
    - Updated localizations
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-04
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/Search_Collection_2_6.pext
    Changelog:
    - Updated localizations
  - Version: 2.7
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Search_Collection_2_7.pext
    Changelog:
    - Updated localizations
  - Version: 2.8
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/Search_Collection_2_8.pext
    Changelog:
    - Updated localizations
  - Version: 2.9
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/Search_Collection_2_9.pext
    Changelog:
    - 'Updated localizations'
    - 'Extension rewritten from scratch'
    - 'Added options to enable and disable default searches'
    - 'Support to add custom searches in settings'
    - 'Search options will now have icons in menu'
  - Version: 2.10
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.20_b118c6cd/Search_Collection_2_10.pext
    Changelog:
    - 'Updated localizations'
    - 'Added option to show IGDB search item in menu. Enabled by default.'