AddonId: ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_0.pext
    Changelog:
    - Initial release
  - Version: 1.1
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_1.pext
    Changelog:
    - Updated localizations
    - Show aspect ratio in resolution menu items
    - Fix menu items not correctly being sorted by resolution
  - Version: 1.2
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-19
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_2.pext
    Changelog:
    - Updated localizations
  - Version: 1.3
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_3.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.2.2
  - Version: 1.4
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_4.pext
    Changelog:
    - Updated localizations
  - Version: 1.5
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_5.pext
    Changelog:
    - Updated localizations
  - Version: 1.6
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_6.pext
    Changelog:
    - Improved extension codebase structure
    - Misc improvements
  - Version: 1.7
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_7.pext
    Changelog:
    - Fix restoring incorrect resolution after exiting game in some cases
  - Version: 1.8
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_8.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.9
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-23
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.23_32f4ed05/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_9.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.10
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.25_aae44e45/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_10.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.11
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-02
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.02_01d659e6/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_11.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.12
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-09
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.09_29543d75/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_12.pext
    Changelog:
    - 'Updated localizations'
    - 'Added support to change Display refresh rate when launching games'
    - 'Improved reliability of changing and restoring display configuration'
    - 'Potential fix for extension failing to restore previous resolution on multi monitor setups'
  - Version: 1.13
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.11_a8e03b9a/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_13.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.14
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.15_9bdaf3ae/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_14.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.15
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.18_1bfa38a6/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_15.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.16
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-06-11
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.06.11_f6b6813d/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_16.pext
    Changelog:
    - 'Updated localizations'
    - 'Performance improvements to games processing'
  - Version: 1.17
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-06-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.06.18_251f0687/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_17.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.18
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-01-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.01.07_6064640d/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_18.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.19
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-02-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.02.15_7796d0ce/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_19.pext
    Changelog:
    - 'Updated links'
  - Version: 1.20
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2023-07-19
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.07.19_7051579c/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_20.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.21
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-08-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.08.18_ceff63a9/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_21.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.22
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-08-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.08.28_553d8252/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_22.pext
    Changelog:
    - 'Updated localizations'
    - 'Improved support for multi-monitor setups'
    - 'Added icons to menu items'
    - 'Moved menu items to game right click context menu'
    - 'Added support to set global configuration in extension setups for Playnite Desktop and Fullscreen Mode'
    - 'Added support to change primary display on game launch by configuring it as a global configuration in extension settings'
    - 'Misc code improvements to fix potential issues that could cause the extension to not work in some cases'
    - 'Changed extension name to "Display Helper"'
  - Version: 1.23
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-08-31
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.08.31_2c93441b/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_23.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.24
    RequiredApiVersion: 6.9.0
    ReleaseDate: 2023-09-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2023.09.27_1fcfc18d/ResolutionChanger_32b6a5c7-be17-4852-b4f7-f059a7321f4c_1_24.pext
    Changelog:
    - 'Changed: Updated localizations'