AddonId: SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_2.pext
    Changelog:
    - Updated localizations
    - Rewriten from scratch as a plugin
    - Options are now available in extensions settings section
  - Version: 2.3
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_3.pext
    Changelog:
    - Fix background music not stopping when launching a game in Fullscreen Mode
    - Updated to Playnite SDK 6.1.0
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_4.pext
    Changelog:
    - Updated localizations
    - Fix splash windows always showing in main screen, even if Playnite is in a secondary monitor
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_5.pext
    Changelog:
    - Updated localizations
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_6.pext
    Changelog:
    - Updated localizations
  - Version: 2.7
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-12
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_7.pext
    Changelog:
    - Updated localizations
  - Version: 2.8
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-12-19
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_8.pext
    Changelog:
    - Updated localizations
    - Added functionality to disable extension for specific games
    - Disable mouse cursor when splashscreen is shown
    - Increase automatic close time of SplashScreen from 30 to 60 seconds
    - Added instructions for temporary fix for Fullscreen controller input issue after closing game in extension settings
  - Version: 2.9
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_9.pext
    Changelog:
    - Updated localizations
    - Option to use global splash image for the SplashScreen
    - Added workaround to fix broken input issue when closing game in fullscreen mode natively in the extension. If you added the script to fix it, you can remove it as it is no longer needed
  - Version: 2.10
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_10.pext
    Changelog:
    - Updated localizations
  - Version: 2.11
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_11.pext
    Changelog:
    - Updated localizations
  - Version: 2.12
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-21
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_12.pext
    Changelog:
    - Updated localizations
    - Fix Playnite mode videos not playing when configured
  - Version: 2.13
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-22
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_13.pext
    Changelog:
    - Updated localizations
  - Version: 2.14
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_14.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.2.2
  - Version: 2.15
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_15.pext
    Changelog:
    - Updated localizations
  - Version: 2.16
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-03
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_16.pext
    Changelog:
    - Updated localizations
  - Version: 2.17
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_17.pext
    Changelog:
    - Updated localizations
  - Version: 2.18
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_18.pext
    Changelog:
    - Updated localizations
  - Version: 2.19
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.9/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_19.pext
    Changelog:
    - Improved extension codebase structure
    - Misc improvements
  - Version: 2.20
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_20.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.21
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.25_aae44e45/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_21.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.22
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.30_901ef791/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_22.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.23
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-03
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.03_3ad2d023/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_23.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.24
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-03
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.03_5555c31b/SplashScreen_d8c4f435-2bd2-49d8-98f6-87b1d415934a_2_24.pext
    Changelog:
    - 'Fix extension causing input issues when exiting games under certain circumstances'
    - 'Removed extension pressing windows key to fix input issues on game close'