AddonId: SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_2.pext
    Changelog:
    - Updated localizations
    - Update to PlayniteSDK.6.0.0
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_3.pext
    Changelog:
    - Updated localizations
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_4.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.1.0
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_5.pext
    Changelog:
    - Updated localizations
    - Fix not launching Steam with the configured actions when game is starting
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_6.pext
    Changelog:
    - Updated localizations
  - Version: 2.7
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/SteamLauncherUtility_31a65402-5b0c-44f0-9fc2-44b22ca4263c_2_7.pext
    Changelog:
    - Updated localizations