AddonId: Nexus_Mods_Checker_ece2874c-be52-4a64-b178-ed379a042f85
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Nexus_Mods_Checker_ece2874c-be52-4a64-b178-ed379a042f85_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/Nexus_Mods_Checker_ece2874c-be52-4a64-b178-ed379a042f85_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/Nexus_Mods_Checker_ece2874c-be52-4a64-b178-ed379a042f85_2_2.pext
    Changelog:
    - Updated localizations
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Nexus_Mods_Checker_ece2874c-be52-4a64-b178-ed379a042f85_2_3.pext
    Changelog:
    - Updated localizations
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Nexus_Mods_Checker_ece2874c-be52-4a64-b178-ed379a042f85_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Nexus_Mods_Checker_ece2874c-be52-4a64-b178-ed379a042f85_2_5.pext
    Changelog:
    - Updated localizations
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/Nexus_Mods_Checker_ece2874c-be52-4a64-b178-ed379a042f85_2_6.pext
    Changelog:
    - Updated localizations
  - Version: 2.7
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/Nexus_Mods_Checker_ece2874c-be52-4a64-b178-ed379a042f85_2_7.pext
    Changelog:
    - Updated localizations
  - Version: 2.8
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Nexus_Mods_Checker_ece2874c-be52-4a64-b178-ed379a042f85_2_8.pext
    Changelog:
    - Updated localizations
  - Version: 2.9
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/Nexus_Mods_Checker_ece2874c-be52-4a64-b178-ed379a042f85_2_9.pext
    Changelog:
    - Updated localizations