AddonId: PlayniteControlLocker_e7c39fe7-bec1-4691-a818-b9ba1470ad21
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.15_d311d23f/PlayniteControlLocker_e7c39fe7-bec1-4691-a818-b9ba1470ad21_1_0.pext
    Changelog:
    - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.16_d599147e/PlayniteControlLocker_e7c39fe7-bec1-4691-a818-b9ba1470ad21_1_1.pext
    Changelog:
    - 'Fix always enabling Control mode'
  - Version: 1.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.17_881638e7/PlayniteControlLocker_e7c39fe7-bec1-4691-a818-b9ba1470ad21_1_2.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.3
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.03.25_aae44e45/PlayniteControlLocker_e7c39fe7-bec1-4691-a818-b9ba1470ad21_1_3.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.4
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-02
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.02_01d659e6/PlayniteControlLocker_e7c39fe7-bec1-4691-a818-b9ba1470ad21_1_4.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.5
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-23
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.23_3f5693d2/PlayniteControlLocker_e7c39fe7-bec1-4691-a818-b9ba1470ad21_1_5.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.6
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-06-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.06.18_251f0687/PlayniteControlLocker_e7c39fe7-bec1-4691-a818-b9ba1470ad21_1_6.pext
    Changelog:
    - 'Updated localizations'