AddonId: SaveFileView_f68f302b-9799-4b77-a982-4bfca97130e2
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/SaveFileView_f68f302b-9799-4b77-a982-4bfca97130e2_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/SaveFileView_f68f302b-9799-4b77-a982-4bfca97130e2_2_1.pext
    Changelog:
      - Updated localizations
      - Fix error during detection of games not from Steam or GOG
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/SaveFileView_f68f302b-9799-4b77-a982-4bfca97130e2_2_2.pext
    Changelog:
    - Updated localizations
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SaveFileView_f68f302b-9799-4b77-a982-4bfca97130e2_2_3.pext
    Changelog:
    - Updated localizations
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/SaveFileView_f68f302b-9799-4b77-a982-4bfca97130e2_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/SaveFileView_f68f302b-9799-4b77-a982-4bfca97130e2_2_5.pext
    Changelog:
    - Updated localizations
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-09
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/SaveFileView_f68f302b-9799-4b77-a982-4bfca97130e2_2_6.pext
    Changelog:
    - Updated localizations
  - Version: 2.7
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/SaveFileView_f68f302b-9799-4b77-a982-4bfca97130e2_2_7.pext
    Changelog:
    - Updated localizations
  - Version: 2.8
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.07_98fa5f6c/SaveFileView_f68f302b-9799-4b77-a982-4bfca97130e2_2_8.pext
    Changelog:
    - 'Updated localizations'
    - 'Full extension rewrite'
    - 'Added support to search for game data if automatic search does not find data'
    - 'Data will be refreshed automatically after closing game'
    - 'Added option to automatically add save directories as game links when obtaining game data'
    - 'Added option to automatically add configuration directories as game links when obtaining game data'
  - Version: 2.9
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-09
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.09_29543d75/SaveFileView_f68f302b-9799-4b77-a982-4bfca97130e2_2_9.pext
    Changelog:
    - 'Updated localizations'