AddonId: Game_Engine_Checker_7a21243e-c7cc-4ca7-85bd-f6f96f22e9db
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/Game_Engine_Checker_7a21243e-c7cc-4ca7-85bd-f6f96f22e9db_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/Game_Engine_Checker_7a21243e-c7cc-4ca7-85bd-f6f96f22e9db_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Game_Engine_Checker_7a21243e-c7cc-4ca7-85bd-f6f96f22e9db_2_2.pext
    Changelog:
    - Updated localizations
  - Version: 2.3
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Game_Engine_Checker_7a21243e-c7cc-4ca7-85bd-f6f96f22e9db_2_3.pext
    Changelog:
    - Updated localizations
  - Version: 2.4
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-20
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/Game_Engine_Checker_7a21243e-c7cc-4ca7-85bd-f6f96f22e9db_2_4.pext
    Changelog:
    - Updated localizations
  - Version: 2.5
    RequiredApiVersion: 6.2.0
    ReleaseDate: 2021-11-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/Game_Engine_Checker_7a21243e-c7cc-4ca7-85bd-f6f96f22e9db_2_5.pext
    Changelog:
    - Updated localizations
  - Version: 2.6
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-09
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/Game_Engine_Checker_7a21243e-c7cc-4ca7-85bd-f6f96f22e9db_2_6.pext
    Changelog:
    - Updated localizations
  - Version: 2.7
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/Game_Engine_Checker_7a21243e-c7cc-4ca7-85bd-f6f96f22e9db_2_7.pext
    Changelog:
    - Updated localizations
  - Version: 2.8
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-07
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.07_98fa5f6c/Game_Engine_Checker_7a21243e-c7cc-4ca7-85bd-f6f96f22e9db_2_8.pext
    Changelog:
    - 'Updated localizations'
    - 'Fix extension failing to obtain data after PCGamingWiki API changes'
  - Version: 2.9
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-06-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.06.18_251f0687/Game_Engine_Checker_7a21243e-c7cc-4ca7-85bd-f6f96f22e9db_2_9.pext
    Changelog:
    - 'Updated localizations'
  - Version: 2.10
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-07-08
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.07.08_f601c982/Game_Engine_Checker_7a21243e-c7cc-4ca7-85bd-f6f96f22e9db_2_10.pext
    Changelog:
    - 'Fix rare error related to paths handling'