AddonId: JastUsaLibrary_d407a620-5953-4ca4-a25c-8194c8559381
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.15_9bdaf3ae/JastUsaLibrary_d407a620-5953-4ca4-a25c-8194c8559381_1_0.pext
    Changelog:
    - 'Initial release'
  - Version: 1.1
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-15
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.15_d5401715/JastUsaLibrary_d407a620-5953-4ca4-a25c-8194c8559381_1_1.pext
    Changelog:
    - 'Fix not importing all games from user library'
  - Version: 1.2
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.18_1bfa38a6/JastUsaLibrary_d407a620-5953-4ca4-a25c-8194c8559381_1_2.pext
    Changelog:
    - 'Updated localizations'
  - Version: 1.3
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-19
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.19_8a60d91b/JastUsaLibrary_d407a620-5953-4ca4-a25c-8194c8559381_1_3.pext
    Changelog:
    - 'Add Source property to "JAST USA" for new added games'
  - Version: 1.4
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-04-23
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2022.04.23_3f5693d2/JastUsaLibrary_d407a620-5953-4ca4-a25c-8194c8559381_1_4.pext
    Changelog:
    - 'Updated localizations'