AddonId: ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3
Packages:
  - Version: 2.0
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-05
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_0.pext
    Changelog:
      - Playnite 9 support
      - Translations support
  - Version: 2.1
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-13
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta2/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_1.pext
    Changelog:
      - Updated localizations
  - Version: 2.2
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-17
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/v2.0-beta3/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_2.pext
    Changelog:
    - Updated localizations
  - Version: 2.3
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-09-30
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-1/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_3.pext
    Changelog:
    - Updated localizations
    - Update to PlayniteSDK.6.0.0
  - Version: 2.4
    RequiredApiVersion: 6.0.0
    ReleaseDate: 2021-10-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_4.pext
    Changelog:
    - Updated localizations
    - Improved rate limit handling for metadata requests
  - Version: 2.5
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_5.pext
    Changelog:
    - Fix in case entry status returned by AniList is null
    - Updated to Playnite SDK 6.1.0
  - Version: 2.6
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-18
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-2/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_6.pext
    Changelog:
    - Updated localizations
  - Version: 2.7
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_7.pext
    Changelog:
    - Updated localizations
    - Add Play Action functionality, providing options to open the game links.
  - Version: 2.8
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-27
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.0-3/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_8.pext
    Changelog:
    - Updated localizations
  - Version: 2.9
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-10-31
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_9.pext
    Changelog:
    - Updated localizations
    - Add functionality to sync Read/Watch status on library update
  - Version: 2.10
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-01
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.1/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_10.pext
    Changelog:
    - Updated localizations
  - Version: 2.11
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-21
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_11.pext
    Changelog:
    - Updated localizations
  - Version: 2.12
    RequiredApiVersion: 6.1.0
    ReleaseDate: 2021-11-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.2/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_12.pext
    Changelog:
    - Fix library update failing when API does not return a entry media format
  - Version: 2.13
    RequiredApiVersion: 6.2.1
    ReleaseDate: 2022-01-16
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.3/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_13.pext
    Changelog:
    - Updated localizations
  - Version: 2.14
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-24
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_14.pext
    Changelog:
    - Updated localizations
    - Updated to Playnite SDK 6.2.2
  - Version: 2.15
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-25
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_15.pext
    Changelog:
    - Updated localizations
  - Version: 2.16
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-01-28
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.7/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_16.pext
    Changelog:
    - Updated localizations
    - Changed the format of the progress value in "Version" field for entries that status is not finished
    - Extension will now update the tag that indicates the entry releasing status on library update
  - Version: 2.17
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-02-14
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_17.pext
    Changelog:
    - Updated localizations
  - Version: 2.18
    RequiredApiVersion: 6.2.2
    ReleaseDate: 2022-03-08
    PackageUrl: https://github.com/darklinkpower/PlayniteExtensionsCollection/releases/download/2.8/ImporterforAnilist_2366fb38-bf25-45ea-9a78-dcc797ee83c3_2_18.pext
    Changelog:
    - Updated localizations